### ISSUE TITLE
Remove Time display 

### ISSUE THREAD

**Issue by web-elite** [ildrm/acf-jalalidatepicker#3]
How do I remove the time display from the field?
![image](https://user-images.githubusercontent.com/49073732/120074804-d7f88700-c0b3-11eb-83bf-27fabb2c3033.png)

**Comment by mkkmail** [comment]
hi. you can change date format according to this document and call Persian date picker script with different format option.
[persian-date document](http://babakhani.github.io/PersianWebToolkit/doc/persian-date/#format  )

**Comment by ShahriarKh** [comment]
Go to `fields > class-ildrm-acf-field-jalali-datepicker-v5.php` & change every
```js
persianDatepicker()
```
to
```js
persianDatepicker({format: 'YYYY/MM/DD'})
```
You can see other formats here: 
https://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/
https://babakhani.github.io/PersianWebToolkit/doc/persian-date/#format

**Comment by web-elite** [comment]
Thanks to all guys✅
